# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# Also see https://dart.dev/tools#ides-and-editors
# Also see https://dart-lang.github.io/linter/lints/

include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.chopper.dart"
    - "lib/src/infrastructure/localization/app_localizations**.dart"
    - pigeons/**
  language:
    strict-casts: true
    strict-inference: true

formatter:
  page_width: 150
  trailing_commas: preserve

linter:
  rules:
    # Ensure package imports are coherent
    always_use_package_imports: false
    prefer_relative_imports: true
    # Ensure code style is coherent
    omit_local_variable_types: false
    prefer_single_quotes: true # or: prefer_double_quotes: true
    # Allow certain code constructs
    avoid_classes_with_only_static_members: false
    avoid_private_typedef_functions: false
    # Clean Code
    avoid_bool_literals_in_conditional_expressions: false
    close_sinks: true
    literal_only_boolean_expressions: true
    only_throw_errors: true
    prefer_adjacent_string_concatenation: true
    unawaited_futures: true
    # use_if_null_to_convert_nulls_to_bools: true # deprecated in Dart 3.11
    # Stricter code constructs (opinionated)
    cascade_invocations: true
    prefer_expression_function_bodies: false
    prefer_foreach: true
    # Problematic with pipeline
    sort_pub_dependencies: false
    use_super_parameters: true
